Add gmp patch to fix configure with gcc 15
This is https://gmplib.org/repo/gmp/rev/8e7bb4ae7a18 rebased on
gmp-6.3.0 with configure updated accordingly.

This fixes a configure test to be compatible with C23, which is the
default in gcc 15.

conftest.c: In function 'f':
conftest.c:12:48: error: too many arguments to function 'g'; expected 0, have 6
   12 | for(i=0;i<1;i++){if(e(got,got,9,d[i].n)==0)h();g(i,d[i].src,d[i].n,got,d[i].want,9);if(d[i].n)h();}}
      |                                                ^ ~
conftest.c:7:6: note: declared here
    7 | void g(){}
      |      ^
configure:6588: $? = 1
<snip>
configure:7310: error: could not find a working compiler, see config.log for details